### ISSUE TITLE
Missing Block Comments

### ISSUE THREAD

**Issue by DerekPeacock** [andreicruceru95/AndreiCruceru-BlueJ#1]
Hi Andrei

I am trying out documenting some of my feedback using Issues, which the way professionals do it.

You much use a block comment for every class (which you have) and every method.  You have used single line comments which are not extracted for API professional documentation.

Please replace all you single line method comments with block comments

**Comment by andreicruceru95** [comment]
Hi Derek,

Thank you for the feedback, it really helps in improving my programming
skills and knowledge.

I will modify my comments, add the missing features and test them. I do not
expect to get 100% marks, and it's only fair because I'm not there yet.

Thank you again for all your help and I look forward to our next session.

Best regards,
Andrei

**Comment by andreicruceru95** [comment]
Hi Derek

Thank you for your feedback.
I have just replaced the single line comments with block comments.

**Comment by DerekPeacock** [comment]
Hi Andrei
That is much better.  You will get pulled up for layout issues from next week including blank lines between the end of a comment and the start of the class.  There are some missing spaces around symbols and unnecessary blank lines.
No point doing anything more to App02 move on to App03
Your mark is


You did not use constants which is why the Functionality mark is not 100%  You used variables, but their values are never changed.
best wishesDerek

    On Sunday, October 11, 2020, 05:44:35 PM GMT+1, Andrei Cruceru <notifications@github.com> wrote:  
 
 


Closed #1.
